# Generated by Django 5.2.3 on 2025-06-15 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.CharField(help_text='Enter your task (max 200 characters)', max_length=200, validators=[django.core.validators.MinLengthValidator(1, 'Task cannot be empty'), django.core.validators.MaxLengthValidator(200, 'Task cannot exceed 200 characters')]),
        ),
    ]
